---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: true
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: install updates (Debian & Ubuntu)
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution in ['Debian', 'Ubuntu']

- hosts: web_servers
  become: true
  tasks:

  - name: install php support and apache (apache2) packages for Deb or Ubu
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install php support and apache (httpd) packages on CentOS
    dnf:
      name:
        -  httpd
        -  php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    dnf:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package: 
      name: samba
      state: latest
