---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: true
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Debian & Ubuntu)
    tags: always
    apt:
      update_cache: true
    changed_when: false
    when: ansible_distribution in ['Debian', 'Ubuntu']

- hosts: all
  become: true
  tasks:
  
  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBdOhWORqnfaA+nuXwwvNSnBPwmOSv19TiFneuHaE605 ansible"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package: 
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: true
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install php support and apache (apache2) packages for Deb or Ubu
    tags: apache, apache2, ubuntu, debian
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install php support and apache (httpd) packages on CentOS
    tags: apache, centos, httpd
    dnf:
      name:
        -  httpd
        -  php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache, httpd, centos
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == 'CentOS'

  - name: change email address for admin
    tags: apache, httpd, centos
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd
    
  - name: second change showing need for different register variable
    tags: apache, httpd, centos
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^dump_example'
      line: dump_example cat_poo
    when: ansible_distribution == "CentOS"
    register: httpd_cat_poo

  - name: restart httpd (CentOS)
    tage: apache, httpd, centos
    service: 
      name: httpd
      state: restarted 
    when: httpd.changed

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos, db, mariadb
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db, mariadb, ubuntu, debian
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest
